sudo: required

language: python

python:
  - "2.7"

# command to install dependencies
install:
  - pip install -U pip setuptools

services:
  - docker

script:
  - test.sh
branches:
  only:
    - master

notifications:
  email: false
